### ISSUE TITLE
Chili-Con-Carne-Rezept hinzufügen

### ISSUE THREAD

**Issue by MhouneyLH** [SynapsenPassi/Rezepte#3]
Ich würde gerne ein Rezept dafür hinzufügen. Schau dir doch mal an, wie lecker das aussieht @SynapsenPassi !!!! Ich würde dafür dein Lasagne-Rezept als Vorlage nehmen.
![image](https://user-images.githubusercontent.com/78447003/198902829-d93a44f6-16e9-48e8-a5e4-37c8bbe4a2d9.png)

**Comment by SynapsenPassi** [comment]
Du hast meine Erlaubnis dies zu tun xD
