### ISSUE TITLE
Ein Template für die PR's hinzufügen

### ISSUE THREAD

**Issue by MhouneyLH** [SynapsenPassi/Rezepte#6]
* du kannst einen neuen Ordner ".github" zum Projekt hinzufügen
* dann die Datei "pull_request_template.md" erstellen und dort mit dem Markdown-Style schreiben, was dann jedes mal bei dem PR vorgefertigt drinnen stehen soll
* ein Beispiel kannst du [hier](https://github.com/MhouneyLH/keystrokemanager/tree/develop/.github) finden 🐔

**Comment by MhouneyLH** [comment]
Das was in der Datei steht, wird dann jedes Mal angezeigt, wenn du eine Beschreibung für einen PR erstellst.

**Comment by SynapsenPassi** [comment]
Ist erledigt

**Comment by MhouneyLH** [comment]
Ich glaube jetzt hatte ich deine Frage verstanden. Ich werde automatisch benachrichtigt, dass das erledigt ist, weil ich ja der Verfasser des Issues war.
